diff -purN a/Makefile b/Makefile
--- a/Makefile	2019-01-19 11:10:58.000000000 +0200
+++ b/Makefile	2019-01-19 18:15:32.160233495 +0200
@@ -1,6 +1,7 @@
 CXXFLAGS += -std=gnu++11 -g3
+CXXFLAGS += -DNV_DRIVER_PATH=\"libGLX_nvidia.so.0\"
 
-all: libprimus_vk.so libnv_vulkan_wrapper.so
+all: libprimus_vk.so libnv_vulkan_wrapper.so primus_vk_diag
 
 libprimus_vk.so: primus_vk.cpp
 	g++ $(CXXFLAGS) -I/usr/include/vulkan -shared -fPIC $^ -o $@
@@ -9,4 +10,4 @@ libnv_vulkan_wrapper.so: nv_vulkan_wrapp
 	g++ $(CXXFLAGS) -I/usr/include/vulkan -shared -fPIC $^ -o $@
 
 primus_vk_diag: primus_vk_diag.o
-	g++ -g3 -o $@ $^ -lX11 -lvulkan -ldl
+	g++ $(CXXFLAGS) -o $@ $^ -lX11 -lvulkan -ldl
