diff -purN a/Makefile b/Makefile
--- a/Makefile	2018-10-16 18:57:51.000000000 +0300
+++ b/Makefile	2018-10-16 19:01:52.082791905 +0300
@@ -1,12 +1,13 @@
-CXXFLAGS += -std=gnu++11 -g3
+PVK_CXXFLAGS=-std=gnu++11 -g
+PVK_NV_DRIVER_PATH=-DNV_DRIVER_PATH=\"libGLX_nvidia.so.0\"
 
 all: libprimus_vk.so libnv_vulkan_wrapper.so
 
 libprimus_vk.so: primus_vk.cpp
-	g++ $(CXXFLAGS) -I/usr/include/vulkan -shared -fPIC $^ -o $@
+	g++ $(CXXFLAGS) $(PVK_CXXFLAGS) $(PVK_NV_DRIVER_PATH) -I/usr/include/vulkan -shared -fPIC $^ -o $@
 
 libnv_vulkan_wrapper.so: nv_vulkan_wrapper.cpp
-	g++ $(CXXFLAGS) -I/usr/include/vulkan -shared -fPIC $^ -o $@
+	g++ $(CXXFLAGS) $(PVK_CXXFLAGS) $(PVK_NV_DRIVER_PATH) -I/usr/include/vulkan -shared -fPIC $^ -o $@
 
 primus-vk-diag: primus_vk_diag.o
 	g++ -g3 -o $@ $^ -lX11 -lvulkan -ldl
